import { createElement } from 'lwc';
import Lwc_31072020_pubsub from 'c/lwc_31072020_pubsub';

describe('c-lwc-31072020-pubsub', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-31072020-pubsub', {
            is: Lwc_31072020_pubsub
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});