import { createElement } from 'lwc';
import Lwc_0708_deleteRecordWithOutApex from 'c/lwc_0708_deleteRecordWithOutApex';

describe('c-lwc-0708-delete-record-with-out-apex', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-0708-delete-record-with-out-apex', {
            is: Lwc_0708_deleteRecordWithOutApex
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});