import { createElement } from 'lwc';
import Lwc_0108_pubsub_subscriber_02 from 'c/lwc_0108_pubsub_subscriber_02';

describe('c-lwc-0108-pubsub-subscriber-02', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-0108-pubsub-subscriber-02', {
            is: Lwc_0108_pubsub_subscriber_02
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});